### ISSUE TITLE
CardRender.js Card Asset Loading & Polished Card Title / Description field

### ISSUE THREAD

**Issue by jasonmzx** [jasonmzx/Black-Jack-Replay-3700U#1]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/68576119/0cf9a346-319d-4523-b091-299131b333b1)

Notice on the Left (In the Game Log) The player pulls:

10 of hearts & Ace of Clubs, but the Cards visually display as Ace of Hearts!

I need you to work on the `CardRender.js` to import all the card types, and based on the incoming props, serve the Correct Card along with an important description of the cards. *(Example: For the hidden card, the naive parser I wrote outputs -1 | of, change this to like "Unknown Card")* 

[CardRender.js Component Full Code](https://github.com/jasonmzx/Black-Jack-Replay-3700U/blob/main/Frontend/blackjack-web/src/components/CardRender.js) 

General Steps to follow for this

**Step 1.**

Find and Download all Card assets you can find, so in total we need 52 pictures, of each unique card as it's own image _(png perferably)_

I think this link has a zip of all of em https://acbl.mybigcommerce.com/52-playing-cards/

Please put these images in the Static sub-directory in the our frontend, make like a subdirectory within static like `card_assets` for ex.

**Step 2.** make sure that based on the incoming props of the CardRender component, the associated card img renders, and the description of the card is well formatted!

**Comment by tahmid-chowdhury** [comment]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/6963175f-9915-4350-9236-3c990a591500)

I'm committing the following changes:
- New card assets sorted by suits/symbols
- Using associated `symbol_name` and `card_value`, the correct card is displayed for all number cards

What's left to do:
- Make a special case for face cards (Jack, Queen, King) and Aces
- The description of the cards requested in the original issue post

**Comment by jasonmzx** [comment]
Ok, close the issue when those are done!

**Comment by tahmid-chowdhury** [comment]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/f2d63318-4342-4987-8ac2-b63d465d9765)

![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/64312929-894a-4ddb-8b6a-d23882f7c548)

The issue regarding the face cards has been resolved. I have reformatted the card descriptions as well as added a special description for the unknown card.

I'm closing the issue here.
