### ISSUE TITLE
CSS & JSX Cleanup of gamelog

### ISSUE THREAD

**Issue by jasonmzx** [jasonmzx/Black-Jack-Replay-3700U#5]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/68576119/63a4541e-0a43-45f5-82dc-c7eed8563532)
Game Log still doesn't look the greatest, even if the text is formatted! Pls go into `Game.js` and fix the rendering of this gamelog

Right now this is the rendering fn, pls spiffy it up!

```javascript
    const RenderLog = (state, hands_payload) => {
        const logStrs = activeGameLoggingAlgorithm(state, hands_payload);

        let logDump = [];

        for (const logStr of logStrs) {
            logDump.push(
                <>
                    <span className="bg-light">
                        {logStr}
                    </span>
                    <br />
                </>
            );
        }

        setGameLog(logDump);
    }
```

I'd say adjust the padding and margins of the span, you can use the Active Logging algorithm with multiple different outputs, like maybe The Card values are rendered differently in the log, and the *Holder* Drew looks different, just make it look better than what it currently is... 

game.js line 233
```html
                        {/* GAME LOG ENTRIES GO INTO HERE */}
                        <div className="ms-2 me-2">
                            {gameLog}
                        </div>
```

Also note you can adjust the container of the gameLog (this is the state the renderer is building too)

**Comment by tahmid-chowdhury** [comment]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/a1d1dee9-4c43-4cbe-88f9-7a0099d1f4ab)

This is what I've got it looking like currently. All I've added is some inline CSS for padding and margins:

```js
<span className="bg-light" style={{ padding: '5px', margin: '5px', display: 'block' }}>
```

Let me know if anything should be changed. Otherwise, I'm closing the issue here.

**Comment by jasonmzx** [comment]
still isn't looking great

**Comment by tahmid-chowdhury** [comment]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/498f33ce-1e9d-4806-8be8-89507efc5599)

Each new card drawn is now displayed in its own block and the line stating the player's hand value is now bolded. The `lg.push()` in `activeGameLoggingAlgorithm()` was updated to the following, where HTML tags are now used to break the message into three distinct parts as well as adding inline CSS where needed to add some space between lines.

```js
            lg.push(
                <div>
                    <span style={{ display: 'block' }}>
                        {`${playerName} drew ${cardDescription} (Value: ${cardValue})`}
                    </span>
                    <br />
                    <span style={{ display: 'block' }}>
                        {`${playerName} cards: ${visibleCards}`}
                    </span>
                    <br />
                    <span>
                        <strong>{`${playerName} hand value: ${totalValue}`}</strong>
                    </span>
                    <br />
                </div>
            )
```

If this is more of the look we were going for, feel free to mark the issue as closed. If not, any advice on how to further improve would be appreciated.

**Comment by tahmid-chowdhury** [comment]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/32552650/08f7c433-42a4-4a8a-b5a8-55551a38ce3f)

The game log now has a scrollbar. The inline CSS used for this is as follows:

```js
                        {/* GAME LOG ENTRIES GO INTO HERE */}
                        <div className="ms-2 me-2">
                            <div style={{ maxHeight: '500px', overflowY: 'auto' }}> {/* `maxHeight` can be adjusted as needed */}
                                {gameLog}
                            </div>
                        </div>
```

Feel free to change the `maxHeight` value and/or remove my comment in the code about being able to do so.
