### ISSUE TITLE
Ace value

### ISSUE THREAD

**Issue by ahmeddarw** [jasonmzx/Black-Jack-Replay-3700U#7]
A player should have the option to choose the value of the ace depending on his situation within the game:

If a player draws a 4 and an ace, he should pick whether if the ace counts as an 11 or as a 1. If the player counts it as an 11 then 4+11=15.
If the player decides to hit after his total cards are equal to 15, and he pulls an ace, the ace should automatically count as a 1 else the player busts.
Ex2. another example: lets say u pull your first card as ACE . u chose the value to be 11 now you pull an ace AGAIN as your second card. you cant choose it as 11 cuz 11+11=22 you will bust so you are forced to make it count as 11+1=12 then if u keep drawing aces they will always count as 1.

**Comment by jasonmzx** [comment]
![image](https://github.com/jasonmzx/Black-Jack-Replay-3700U/assets/68576119/16d6f5db-d0a6-4b55-b7e6-e92e0a09653f)

I'm going to keep it in the way, which it allocates the aces value, upon every card entry to ultimately max the players hand value whilst minimizing it to be under 21, if possible

According to a guy on reddit
